### ISSUE TITLE
PAanno error

### ISSUE THREAD

**Issue by Eduardo-Auer** [PreMedKB/PAnno#4]
Hello,
I am having some issues that does not let PAanno analyze my genome vcf. I have done GATK best practices and QC in my genome data and when I run PAnno command (`panno -s NG1U1B2ET6 -i /mnt/c/Users/Administrador/Documents/NG1U1B2ET6_all_variants_PASS_only_filter_ID.vcf.gz -p LAT -o /mnt/c/Users/Administrador/Documents/`), the following error appears: 
```

Parsing PGx related diplotypes ...
Traceback (most recent call last):
  File "/root/mambaforge-pypy3/envs/panno/bin/panno", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/mambaforge-pypy3/envs/panno/lib/python3.12/site-packages/panno/panno.py", line 101, in main
    dic_diplotype, dic_rs2gt, hla_subtypes = genotype_resolution.resolution(pop_dic[population], germline_vcf)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mambaforge-pypy3/envs/panno/lib/python3.12/site-packages/panno/genotype_resolution.py", line 18, in resolution
    for line in file:
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Do you know what problem might be?

**Comment by wilkb777** [comment]
This error message isn't super helpful at indicating that PAnno appears to only take uncompressed VCF files. I didn't see it listed in the README anywhere but if you look [at the example VCFs provided](https://github.com/PreMedKB/PAnno-analysis/tree/main/vcf) they are all uncompressed. I tried running with a gzip compressed VCF at first and had the same error  and was able to succefully run PAnno after just unzipping the VCF file and using that.

**Comment by Eduardo-Auer** [comment]
> This error message isn't super helpful at indicating that PAnno appears to only take uncompressed VCF files. I didn't see it listed in the README anywhere but if you look [at the example VCFs provided](https://github.com/PreMedKB/PAnno-analysis/tree/main/vcf) they are all uncompressed. I tried running with a gzip compressed VCF at first and had the same error and was able to succefully run PAnno after just unzipping the VCF file and using that.

Thank you! It worked! 
Best regards,
Eduardo.
